apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.apps.python.svc.name }}
  annotations:
    {{- include "zeebo.annotations" . | nindent 4 }}
  labels:
    {{- include "zeebo.labelsPython" . | nindent 4 }}
spec:
  maxUnavailable: 50%
  selector:
    matchLabels:
      {{- include "zeebo.selectorLabelsPython" . | nindent 6 }}
