ingress:
  hostname: zeebo

images:
  python:
    repository: neverping/zeebo-python
  go:
    repository: neverping/zeebo-go
  pullPolicy: Always

apps:
  go:
    svc:
      name: "zeebo-go"
    envs:
      port: 4458
      requestTimeout: 5
      idleTimeout: 10
    probes:
      readinessProbe:
        initialDelaySeconds: 5
        tcpSocket:
          port: 4458
      livenessProbe:
        initialDelaySeconds: 5
        tcpSocket:
          port: 4458
  python:
    svc:
      name: "zeebo-python"
    envs:
      port: 50051
    probes:
      readinessProbe:
        initialDelaySeconds: 5
        tcpSocket:
          port: 50051
      livenessProbe:
        initialDelaySeconds: 5
        tcpSocket:
          port: 50051

# The team owning this chart
team: "devops"
repository: https://github.com/neverping/zeebo-app

# Resource for the service
# requests: When using the amount of memory the service is marked as a candidate for termination in case
#           of out of memory on the node
# limits: if the service reaches this amount it WILL be restarted
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 500m
    memory: 512Mi

# number of instance to run
replicaCount: 1

# Upgrade strategy - RollingUpdate is currently the best strategy so far.
upgrade:
  strategy: RollingUpdate
  maxSurge: 1
  maxUnavailable: 1